// Client-side takeaway exports — no Gemini calls, no server. Turns a RunResult into
// an Architecture Decision Record (markdown) and a scaffolding prompt for a coding agent.

import type { RunResult, Variant } from '../types';

export const APP_URL = 'https://blueprint.build';

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'blueprint';
}

export function adrFilename(run: RunResult): string {
  return `adr-${slugify(run.topic)}.md`;
}

function sourceRefs(ids: string[]): string {
  return ids.map((id) => `[${id}]`).join('');
}

function variantSection(v: Variant): string {
  const lines: string[] = [];
  lines.push(`### ${v.name} — ${v.profile}`);
  lines.push(`> ${v.tagline}`);
  lines.push('');
  lines.push(v.summary);
  lines.push('');
  lines.push('```mermaid');
  lines.push(v.mermaid.trim());
  lines.push('```');
  lines.push('');
  lines.push('**Components**');
  for (const c of v.components) {
    const refs = c.sourceIds.length ? ` ${sourceRefs(c.sourceIds)}` : '';
    lines.push(`- **${c.name}** — ${c.role}${refs}`);
  }
  lines.push('');
  lines.push(`**Risks:** ${v.risks}`);
  lines.push('');
  lines.push(`**Choose this when:** ${v.whenToChoose}`);
  return lines.join('\n');
}

export function buildAdrMarkdown(run: RunResult): string {
  const date = new Date().toISOString().slice(0, 10);
  const out: string[] = [];

  out.push(`# ADR: ${run.topic}`);
  out.push('');
  out.push(`${date} · Generated by [Blueprint](${APP_URL})`);
  out.push('');

  // Context
  out.push('## Context');
  out.push('');
  out.push(`- **Topic:** ${run.topic}`);
  if (run.docName) out.push(`- **Source document:** ${run.docName}`);
  if (run.repoUrl) out.push(`- **Repository:** ${run.repoUrl}`);
  if (run.chosenInterpretation) out.push(`- **Chosen interpretation:** ${run.chosenInterpretation}`);
  if (run.constraints?.length) {
    out.push('- **Constraints:**');
    for (const c of run.constraints) out.push(`  - ⚑ ${c}`);
  }
  out.push('');

  // Options considered
  out.push('## Options considered');
  out.push('');
  out.push(run.variants.map(variantSection).join('\n\n'));
  out.push('');

  // Trade-offs table
  out.push('## Trade-offs');
  out.push('');
  out.push(`| Criterion | ${run.variants.map((v) => v.name).join(' | ')} |`);
  out.push(`| --- | ${run.variants.map(() => '---').join(' | ')} |`);
  for (const row of run.comparison) {
    out.push(`| ${row.criterion} | ${row.values.join(' | ')} |`);
  }
  out.push('');

  // Decision
  out.push('## Decision');
  out.push('');
  out.push('_Pending — pick a variant_');
  out.push('');

  // Sources
  out.push('## Sources');
  out.push('');
  run.sources.forEach((s, i) => {
    const meta = s.meta ? ` · ${s.meta}` : '';
    out.push(`${i + 1}. [${s.id}] [${s.title}](${s.url}) — ${s.origin}${meta}`);
  });
  out.push('');

  return out.join('\n');
}

export function buildAgentPrompt(run: RunResult, variantIndex: number): string {
  const v = run.variants[Math.max(0, Math.min(variantIndex, run.variants.length - 1))];
  const out: string[] = [];

  out.push('You are a coding agent scaffolding a new project. Follow this architecture.');
  out.push('');
  out.push('# Goal');
  out.push(`Build: ${run.topic}`);
  if (run.chosenInterpretation) out.push(`Interpretation: ${run.chosenInterpretation}`);
  out.push(`Chosen architecture: **${v.name}** (${v.profile}) — ${v.tagline}`);
  out.push('');
  out.push(v.summary);
  out.push('');

  out.push('# Components to implement');
  for (const c of v.components) {
    const refs = c.sourceIds.length ? ` (see ${sourceRefs(c.sourceIds)})` : '';
    out.push(`- **${c.name}** — ${c.role}${refs}`);
  }
  out.push('');

  out.push('# Hard constraints (do not violate)');
  if (run.constraints?.length) {
    for (const c of run.constraints) out.push(`- ⚑ ${c}`);
  } else {
    out.push('- None specified.');
  }
  out.push('');

  out.push('# Sources to cite and consult');
  run.sources.forEach((s) => out.push(`- [${s.id}] ${s.title} — ${s.url}`));
  out.push('');

  out.push('# Working agreement');
  out.push('Cite or consult the sources above when implementing each component. Ask before deviating from this architecture or dropping any hard constraint.');
  out.push('');
  out.push(`_Scaffolded from Blueprint — ${APP_URL}_`);

  return out.join('\n');
}
