// Generate real, live example runs and write them to examples.generated.ts at repo root.
// Runs the full pipeline sequentially on two topics with a 30s pause between them,
// validates each with the same 4 checks pipeline-smoke uses, and only writes on success.

// One env var works everywhere: gemini.ts reads process.env.API_KEY.
process.env.API_KEY ||= process.env.GEMINI_API_KEY;

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { analyzeSources, scoutQueries, synthesizeArchitectures } from '../services/gemini';
import { gatherSources } from '../services/sources';
import type { RunResult } from '../types';

const TOPICS = [
  'distributed database built on AI agents',
  'AI code-review copilot for monorepos',
];

// Same 4 checks as scripts/pipeline-smoke.ts. Returns the list of failures (empty = all pass).
function validate(run: RunResult): string[] {
  const fails: string[] = [];
  if (run.variants.length < 2) fails.push(`<2 variants (got ${run.variants.length})`);
  if (run.variants.some((v) => !v.mermaid?.trim())) fails.push('a variant has empty mermaid');
  const ids = new Set(run.sources.map((s) => s.id));
  const dangling = run.variants.flatMap((v) => v.components.flatMap((c) => c.sourceIds)).filter((id) => !ids.has(id));
  if (dangling.length) fails.push(`dangling sourceIds: ${[...new Set(dangling)].join(', ')}`);
  if (run.comparison.some((r) => r.values.length !== run.variants.length)) fails.push('comparison row length != variants');
  return fails;
}

async function runOne(topic: string): Promise<RunResult> {
  const q = await scoutQueries(topic);
  const sources = await gatherSources(q.arxivQueries, q.githubQueries, (m) => console.log(`    · ${m}`));
  const insights = await analyzeSources(topic, sources);
  const { variants, comparison } = await synthesizeArchitectures(topic, sources, insights);
  return { topic, sources, insights, variants, comparison };
}

async function main(): Promise<void> {
  if (!process.env.API_KEY) {
    console.error('Missing API_KEY / GEMINI_API_KEY in environment.');
    process.exit(1);
  }

  const runs: RunResult[] = [];
  for (let i = 0; i < TOPICS.length; i++) {
    const topic = TOPICS[i];
    console.log(`\n=== [${i + 1}/${TOPICS.length}] "${topic}" ===`);
    const t0 = Date.now();
    const run = await runOne(topic);
    console.log(`  generated in ${Date.now() - t0}ms — sources: ${run.sources.length}, variants: ${run.variants.length}`);

    const fails = validate(run);
    if (fails.length) {
      console.error(`  VALIDATION FAILED: ${fails.join('; ')}`);
      process.exit(1);
    }
    console.log('  validation: ALL PASS');
    runs.push(run);

    if (i < TOPICS.length - 1) {
      console.log('  pausing 30s to stay under the rate limit…');
      await new Promise((r) => setTimeout(r, 30_000));
    }
  }

  // Plain TS module — data is inlined (no JSON import), so it works in AI Studio's
  // no-bundler environment. The `import type` is erased at compile time.
  const body = JSON.stringify(runs, null, 2);
  const out = `import type { RunResult } from './types';

// AUTO-GENERATED by scripts/generate-examples.ts — do not edit by hand.
// Real live pipeline runs captured ${new Date().toISOString()}.
// Regenerate: npm run examples
export const EXAMPLE_RUNS: RunResult[] = ${body};
`;
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  writeFileSync(join(root, 'examples.generated.ts'), out);
  console.log(`\nWrote examples.generated.ts — ${runs.length} runs.`);
}

main();
